import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { SessionProvider } from "next-auth/react";
import { AppSidebar } from "../_components/dashboard/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { Footer } from "~/app/_components/footer";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function Layout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" className={`${geist.variable}`}>
			<body>
				<SessionProvider>
					<TRPCReactProvider>
           <SidebarProvider>
             {/* Make a flex container so sidebar sits beside the main area */}
             <div className="flex h-screen w-screen">
               <AppSidebar />
               <main className="flex-1 flex flex-col items-center justify-center">
                 <SidebarTrigger />
                 {children}
                 <Footer />
               </main>
             </div>
           </SidebarProvider>
			</TRPCReactProvider>
				</SessionProvider>
			</body>
		</html>
	);
}
